version: '3'

services:

  nginx:
    image: poktnetwork/nginx:dispatch
    build: ../nginx/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "../nginx/conf.d/10-pocket.conf:/etc/nginx/conf.d/default.conf"
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf"
    
    networks:
      - pocket

  geth-rinkeby:
    image: ethereum/client-go:stable
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-rinkeby:/.mainnet

    command: "--rinkeby --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .testnet --verbosity 3"
    networks:
      - pocket

  geth-mainnet:
    image: ethereum/client-go:stable
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - geth-mainnet:/.mainnet

    command: "--rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3" 
    networks:
      - pocket

  aion-mainnet:
    image: aionnetwork/aionr:0.2.4
    expose:
      - "8545"
      - "8547"
      - "30303"
    volumes:
      - aion-mainnet:/root/.aion

    environment:
      java_api_listen_address: "0.0.0.0"
      rpc_listen_address: "0.0.0.0"
      AION_NETWORK: "mainnet"
    networks:
      - pocket

  aion-mastery:
    build: ../aion/aion-mastery/.
    image: poktnetwork/aion:mastery 
    expose:
      - "8545"
      - "8547"
      - "30303"
    volumes:
      - aion-mastery:/root/.aion

    environment:
      java_api_listen_address: "0.0.0.0"
      rpc_listen_address: "0.0.0.0"
      AION_NETWORK: "mastery"
    networks:
      - pocket

  tezos-mainnet:
    image: tezos/tezos:mainnet 
    expose:
      - '8732'
      - '9732'
    volumes:
      - mainnet-node-data:/var/run/tezos/node
      - mainnet-client-data:/var/run/tezos/client
    
    command: tezos-node
    networks:
      - pocket

  tezos-alphanet:
    image: tezos/tezos:alphanet
    expose:
      - '8732'
      - '9732'
    volumes:
      - alphanet-node-data:/var/run/tezos/node
      - alphanet-client-data:/var/run/tezos/client
    
    command: tezos-node
    networks:
      - pocket

  pocket-service:
    image: poktnetwork/pocket-core:${ENV:-mvp-staging-latest}
    build: ./.. 
    ports:
      - "8081:8081"
    
    command: --datadirectory datadir --disip ${POCKET_DISPATCH_IP-dispatch.pokt.network} --gid ${POCKET_SERVICE_GID} --ip localhost --disrport 80 --port 8081 --requestTimeout 0
    environment:
      POCKET_CORE_START_DELAY: 180 
      POCKET_CORE_CHAINS: '[{"blockchain":{"name":"AION","netid":"256","version":"0"},"url":"aion-mainnet:8545"},{"blockchain":{"name":"AION","netid":"32","version":"0"},"url":"aion-mastery:8545"},{"blockchain":{"name":"ETH","netid":"1","version":"0"},"url":"geth-mainnet:8545"},{"blockchain":{"name":"ETH","netid":"4","version":"0"},"url":"geth-rinkeby:8545"},{"blockchain":{"name":"TEZOS","netid":"MAINNET","version":"0"},"url":"tezos-mainnet:8732"},{"blockchain":{"name":"TEZOS","netid":"ALPHANET","version":"0"},"url":"tezos-alphanet:8732"},{"blockchain":{"name":"POA","netid":"99","version":"0"},"url":"POA-mainnet:8545"},{"blockchain":{"name":"POA","netid":"77","version":"0"},"url":"POA-testnet:8545"},{"blockchain":{"name":"POA","netid":"100","version":"0"},"url":"POA-xdai:8545"}]'
    networks:
      - pocket

  POA-testnet:
    image: ethereum/client-go:stable
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-testnet:/.testnet

    command: "--rinkeby --networkid 77 --rpc --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .testnet --verbosity 3"
    networks:
      - pocket

  POA-xdai:
    image: ethereum/client-go:stable
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-xdai:/.mainnet

    command: "--rpc --networkid 100 --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3" 
    networks:
      - pocket
  
  POA-mainnet:
    image: ethereum/client-go:stable
    expose:
      - "8545"
      - "8546"
      - "30303"
    volumes:
      - POA-mainnet:/.mainnet

    command: "--rpc --networkid 99 --rpcapi eth,net --rpcaddr 0.0.0.0 --rpcport 8545 --rpcvhosts=* --syncmode fast --datadir .mainnet --verbosity 3" 
    networks:
      - pocket

volumes:
  # AION
  aion-mainnet:
  aion-mastery:
  # GETH
  geth-mainnet:
  geth-rinkeby:
  # TEZOS
  alphanet-client-data:
  alphanet-node-data:
  mainnet-client-data:
  mainnet-node-data:
  # POA
  POA-mainnet:
  POA-testnet:
  POA-xdai:

networks:
  pocket:
    driver: bridge
